### ISSUE TITLE
Sketches

### ISSUE THREAD

**Issue by EvanAG** [EvanAG/the-lunchbox-fund#1]

**Comment by EvanAG** [comment]
![skecthes-1_page_1](https://cloud.githubusercontent.com/assets/6333804/5783284/8f97ae9e-9d8f-11e4-8c40-900a5cd366b4.jpg)
![skecthes-1_page_2](https://cloud.githubusercontent.com/assets/6333804/5783287/8fa0fd1e-9d8f-11e4-8d0a-56e9adbb879d.jpg)
![skecthes-1_page_3](https://cloud.githubusercontent.com/assets/6333804/5783285/8f9e4592-9d8f-11e4-9273-6e7ea29b33d1.jpg)
![skecthes-1_page_4](https://cloud.githubusercontent.com/assets/6333804/5783286/8f9e8160-9d8f-11e4-8653-57c4d536d3fd.jpg)
![skecthes-1_page_5](https://cloud.githubusercontent.com/assets/6333804/5783288/8fa2e8f4-9d8f-11e4-8668-1ad0c94bba83.jpg)

**Comment by Hasan-Yavuz** [comment]
![sketch_1](https://cloud.githubusercontent.com/assets/6333800/5849449/cd7a9316-a1b3-11e4-9402-d6229ca1d9a1.jpeg)
![sketch_2](https://cloud.githubusercontent.com/assets/6333800/5849450/cd7de28c-a1b3-11e4-963c-78c5a7e832ac.jpeg)
