### ISSUE TITLE
Trends

### ISSUE THREAD

**Issue by Hasan-Yavuz** [EvanAG/the-lunchbox-fund#10]

**Comment by EvanAG** [comment]
TRENDS

Full width images and videos

Large footer

Less navigation items

Less busy

Clean

Side navigation

Images in grid

Minimalistic

Responsive

Ghost buttons with subtle hover animations

Bigger emphasis on typography

Scrolling over clicking - easier to do and less loading times

Microinteractions (pop-ups ie. email signup)
