### ISSUE TITLE
Competitive Analysis

### ISSUE THREAD

**Issue by EvanAG** [EvanAG/the-lunchbox-fund#2]

**Comment by Hasan-Yavuz** [comment]
![screen shot 2015-01-09 at 8 59 40 am](https://cloud.githubusercontent.com/assets/6333800/5782927/cc719224-9d8c-11e4-88e5-6916e4485525.png)
![screen shot 2015-01-09 at 8 59 48 am](https://cloud.githubusercontent.com/assets/6333800/5782926/cc717bd6-9d8c-11e4-8e52-307547f4e37d.png)
![screen shot 2015-01-09 at 9 02 07 am](https://cloud.githubusercontent.com/assets/6333800/5782930/cc720132-9d8c-11e4-8ade-90e02d753a37.png)
![screen shot 2015-01-09 at 9 06 26 am](https://cloud.githubusercontent.com/assets/6333800/5782928/cc71adfe-9d8c-11e4-8c65-8a621778942d.png)
![screen shot 2015-01-09 at 9 06 28 am](https://cloud.githubusercontent.com/assets/6333800/5782925/cc715246-9d8c-11e4-9047-6badac8610e1.png)
![screen shot 2015-01-09 at 9 07 27 am](https://cloud.githubusercontent.com/assets/6333800/5782929/cc71f408-9d8c-11e4-9cb4-82e55ec81e5b.png)
![screen shot 2015-01-09 at 9 07 30 am](https://cloud.githubusercontent.com/assets/6333800/5782932/cc7e304c-9d8c-11e4-88c8-d49d6043c2a5.png)
![screen shot 2015-01-09 at 9 08 14 am](https://cloud.githubusercontent.com/assets/6333800/5782933/cc7e884e-9d8c-11e4-93a6-9bc5a1bb55bd.png)
![screen shot 2015-01-09 at 9 08 17 am](https://cloud.githubusercontent.com/assets/6333800/5782936/cc807d0c-9d8c-11e4-8968-040038093381.png)
![screen shot 2015-01-09 at 9 08 38 am](https://cloud.githubusercontent.com/assets/6333800/5782931/cc7aa116-9d8c-11e4-9b38-3b5cdf6f36ac.png)
![screen shot 2015-01-09 at 9 08 40 am](https://cloud.githubusercontent.com/assets/6333800/5782934/cc7fd6ae-9d8c-11e4-8e8d-5d2cec90e3dd.png)
![screen shot 2015-01-09 at 9 09 06 am](https://cloud.githubusercontent.com/assets/6333800/5782935/cc8004c6-9d8c-11e4-9883-3ed36f0b59b1.png)
![screen shot 2015-01-09 at 9 09 15 am](https://cloud.githubusercontent.com/assets/6333800/5782937/cc869656-9d8c-11e4-8a1c-de8ada3fb3d5.png)
![screen shot 2015-01-09 at 9 09 24 am](https://cloud.githubusercontent.com/assets/6333800/5782939/cc8ba4fc-9d8c-11e4-9dd9-7ce8ba6de0d9.png)
![screen shot 2015-01-09 at 9 09 36 am](https://cloud.githubusercontent.com/assets/6333800/5782938/cc8adcde-9d8c-11e4-8a85-3dcac2f2c62f.png)
![screen shot 2015-01-09 at 9 09 38 am](https://cloud.githubusercontent.com/assets/6333800/5782940/cc8c52e4-9d8c-11e4-8ff5-42ce2514bed0.png)
