### ISSUE TITLE
Inspiration

### ISSUE THREAD

**Issue by EvanAG** [EvanAG/the-lunchbox-fund#3]

**Comment by Hasan-Yavuz** [comment]
![061232066ac55d8dbd41c9aa16bd2292](https://cloud.githubusercontent.com/assets/6333800/5782879/93c3dc7a-9d8c-11e4-9239-1d1d1fb471e3.jpg)
![non-profit-homepage](https://cloud.githubusercontent.com/assets/6333800/5782874/93be7ee2-9d8c-11e4-8b9e-e453a9cd858f.jpg)
![screen shot 2015-01-09 at 11 40 37 am](https://cloud.githubusercontent.com/assets/6333800/5782876/93bedaea-9d8c-11e4-8f2e-6c06f2bc8d76.png)
![screen shot 2015-01-09 at 11 40 52 am](https://cloud.githubusercontent.com/assets/6333800/5782877/93bff74a-9d8c-11e4-9621-9886b6d10888.png)
![screen shot 2015-01-09 at 11 41 49 am](https://cloud.githubusercontent.com/assets/6333800/5782878/93c0a028-9d8c-11e4-9af7-bf0dd550d10e.png)
![screen shot 2015-01-09 at 11 41 51 am](https://cloud.githubusercontent.com/assets/6333800/5782875/93be8a90-9d8c-11e4-8587-2df5bd4975f9.png)
![screen shot 2015-01-09 at 11 42 50 am](https://cloud.githubusercontent.com/assets/6333800/5782882/93d3a740-9d8c-11e4-82d9-ac3dd0b0c0ef.png)
![screen shot 2015-01-09 at 11 44 20 am](https://cloud.githubusercontent.com/assets/6333800/5782880/93cc22d6-9d8c-11e4-8c2b-17e160a802a1.png)
![screen shot 2015-01-09 at 11 44 37 am](https://cloud.githubusercontent.com/assets/6333800/5782881/93cda908-9d8c-11e4-9332-1224dc04df59.png)

**Comment by EvanAG** [comment]
http://www.ru4children.org/#home

![screen shot 2015-01-16 at 2 49 02 pm](https://cloud.githubusercontent.com/assets/6333804/5783191/e0eca106-9d8e-11e4-8ff5-2d8feae06e45.png)

**Comment by EvanAG** [comment]
https://mvmt.org/

![screen shot 2015-01-16 at 2 50 04 pm](https://cloud.githubusercontent.com/assets/6333804/5783209/01764ec2-9d8f-11e4-981f-9b1b16ebbc5c.png)
