### ISSUE TITLE
Personas

### ISSUE THREAD

**Issue by Hasan-Yavuz** [EvanAG/the-lunchbox-fund#9]

**Comment by namasteChris** [comment]
![lunchboxdonor](https://cloud.githubusercontent.com/assets/5443889/5809631/b9cbcbde-a008-11e4-96c0-ce583d6a8c11.jpg)
![lunchboxsponsor](https://cloud.githubusercontent.com/assets/5443889/5809632/b9cbef06-a008-11e4-87a6-345e983c0b79.jpg)
![lunchboxvolunteer](https://cloud.githubusercontent.com/assets/5443889/5809633/b9d300c0-a008-11e4-84e7-4f6443ef5afc.jpg)
